export enum OrderStatus {
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
  CONFIRMADO = 'CONFIRMADO',
  EM_PREPARO = 'EM_PREPARO',
  PRONTO = 'PRONTO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}

export enum OrderChannel {
  APP = 'APP',
  TOTEM = 'TOTEM',
  BALCAO = 'BALCAO',
  WEB = 'WEB',
}
